version: '2.4'
services:
  web:
    build: .
    image: codeigniter-test:1.0
    ports:
      - 80:80
    volumes:
      - ./ci:/var/www/html
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ejercicio
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - codeigniter-data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db

volumes:
  codeigniter-data:
    driver: local